# base image
from python:3.12.2-alpine

# define working directory
workdir /app

# install packages
run pip install "fastapi[standard]"
run pip install psycopg2-binary
run pip install pandas

# copy all files from this folder to the container's filesystem
copy . .

# run command
cmd ["fastapi", "run", "--port", "80"]